### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by oleh-panasiuk** [oleh-panasiuk/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by fakeaccpanasiuk** [comment]
September 2019 - present
Studying for a master's degree in computer engineering.

Septeber 2015 - June 2019
Received a bachelor's degree in computer engineering.

September 2004 - May 2015
Graduated from high school.
